apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkdocs-dev-deployment
  namespace: mkdocs-dev
  labels:
    app: mkdocs-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mkdocs-dev
  template:
    metadata:
      labels:
        app: mkdocs-dev
    spec:
      containers:
      - name: mkdocs
        image: minidocks/mkdocs
        workingDir: /app
        args: ["serve", "-a", "0.0.0.0:8000", "-t", "readthedocs"]
        ports:
        - containerPort: 8000
          name: http
        volumeMounts:
        - name: mkdocs-storage
          mountPath: /app
        # Using subPath to inject specific files into the mounted PVC directory
        - name: mkdocs-config
          mountPath: /app/mkdocs.yml
          subPath: mkdocs.yml
        #- name: mkdocs-content
        #  mountPath: /app/docs/index.md
        #  #subPath: index.md
      volumes:
      - name: mkdocs-storage
        persistentVolumeClaim:
          claimName: mkdocs-dev-pvc
      - name: mkdocs-config
        configMap:
          name: mkdocs-config-map
      #- name: mkdocs-content
      #  configMap:
      #    name: mkdocs-content-map