apiVersion: v1
kind: Service
metadata:
  name: mkdocs-dev-svc
  namespace: mkdocs-dev
  labels:
    app: mkdocs-dev-svc
    app.kubernetes.io/instance: mkdocs-dev-svc
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
    nodePort: 30583
  selector:
    app: mkdocs-dev
