apiVersion: v1
kind: PersistentVolume
metadata:
  name: mkdocs-dev-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mkdocs-dev-pvc
    namespace: mkdocs-dev
  hostPath:
    path: /mnt/nfs_share01/pi4/pv/apps/mkdocs-dev
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mkdocs-dev-pvc
  namespace: mkdocs-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ''
  volumeMode: Filesystem
  volumeName: mkdocs-dev-pv
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
